// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BGbuk35HSl_ooT39VfumX_cLRQCg-VQ',
    appId: '1:44150089003:web:e69079ffef23d1b4f2916e',
    messagingSenderId: '44150089003',
    projectId: 'bam-literacy-app',
    authDomain: 'bam-literacy-app.firebaseapp.com',
    storageBucket: 'bam-literacy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdofqgVLcR-ieQHPBFLgJxy02vmrceSo4',
    appId: '1:44150089003:android:967aa6903fe5ab1cf2916e',
    messagingSenderId: '44150089003',
    projectId: 'bam-literacy-app',
    storageBucket: 'bam-literacy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4S7179xlWJA_ympqIeh8Hc7twFq_xm4E',
    appId: '1:44150089003:ios:8c279b4021a9af68f2916e',
    messagingSenderId: '44150089003',
    projectId: 'bam-literacy-app',
    storageBucket: 'bam-literacy-app.firebasestorage.app',
    iosBundleId: 'org.robotsmali.literacyApp',
  );

}